### ISSUE TITLE
Calculate shapes of Satellite Galaxies of one Simulation run

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vela_satellites#1]
Calculate and organize in satellite pandas DB, its satellite shapes

DOD - pandas table of galaxynumber=01 satellite galaxies shapes (1kpc, 0.5kpc, Rsat, R0,9coldgas, Reff)

**Comment by tussbaum** [comment]
Why numOfpoints_start < numOfpoints_end?

**Comment by Beilinson** [comment]
Check why iter=1 sometimes

**Comment by tussbaum** [comment]
For every option that the code does not return shape, write in special columns why it stopped (too many iterations, a small number of particles<20, small radius<0.10 kpc, etc)

**Comment by Beilinson** [comment]
if statement that checks if already ran on that satellite
