### ISSUE TITLE
shape calculation - if already ran on that satellite

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vela_satellites#3]

**Comment by Beilinson** [comment]
added variable:
sgal_shape_df['calculated']=np.full(len(sgal_shape_df), False, dtype=bool)


In beginning of loop:
if sgal_shape_df.iloc[i]['calculated']==True:
            i+=1
            continue

at end of loop(if it got through the first if statement):
        sgal_shape_df.loc[index,['calculated']]=True

**Comment by tussbaum** [comment]
Great! Move the relevant issue in the
