### ISSUE TITLE
Pearson Linear Correlation

### ISSUE THREAD

**Issue by Beilinson** [GalaxyHunters/Vela_satellites#45]
DOD - Check if parameters are normalized, if not normalize and redo the graph + important features
Check Logarithmic variables
Normalize data

**Comment by tussbaum** [comment]
0. Expand the data by 2: Take one snapshot before entering Rvir and one after (put some label so we could find out later)
**1. Normalize including log wherever is needed!**
2. What features are correlative or counter-corelative (high, above 0.6), example: Sigma_stars(Rsat) and Sigma_stars(0.5kpc) should be corelative.
3.  What features are correlative or counter-corelative to the Qlabel

**Comment by Beilinson** [comment]
Normalizing the data has negligible effect on linear correlation:

NON-NORMALIZED:
Mcg(Rcoldgass_0.9)[Msun]        0.396314
Mcg(Rsat)[Msun]                 0.500710
Mdm(R0.5kpc)[Msun]              0.469421
Mdm(Rsat)[Msun]                 0.521141
Mgas(R0.5kpc)[Msun]             0.388407
Mgas(Rsat)[Msun]                0.498700
Mstar(R0.5kpc)[Msun]            0.458007
Mstar(Rsat)[Msun]               0.542477
Mstar_young(Rsat)[Msun]         0.391147
Mtot(R0.5kpc)[Msun]             0.488779
Mtot(Rsat)[Msun]                0.546137
Rsat[kpc]                       0.411941
Mcg(R0.5kpc)[Msun]              0.387350
Msat/Mrvir                      0.453209
density(R0.5kpc)[Msun/kpc^3]    0.458007
density(R1kpc)[Msun/kpc^3]      0.484345
density(Rsat)[Msun/kpc^3]       0.360060
sigma(R0.5kpc)[Msun/kpc^2]      0.458007
sigma(Rsat)[Msun/kpc^2]         0.439603

NORMALIZED:
Mcg(Rcoldgass_0.9)[Msun]        0.457564
Mcg(Rsat)[Msun]                 0.516973
Mdm(R0.5kpc)[Msun]              0.357762
Mdm(Rsat)[Msun]                 0.481405
Mgas(R0.5kpc)[Msun]             0.360414
Mgas(Rsat)[Msun]                0.519434
Mstar(R0.5kpc)[Msun]            0.520115
Mstar(Rsat)[Msun]               0.554430
Mstar_young(R0.5kpc)[Msun]      0.387190
Mstar_young(Rsat)[Msun]         0.434383
Mtot(R0.5kpc)[Msun]             0.519654
Mtot(Rsat)[Msun]                0.537578
Rsat[kpc]                       0.409052
Mcg(R0.5kpc)[Msun]              0.352462
Msat/Mrvir                      0.484960
density(R0.5kpc)[Msun/kpc^3]    0.520115
density(R1kpc)[Msun/kpc^3]      0.534665
density(Rsat)[Msun/kpc^3]       0.348769
sigma(R0.5kpc)[Msun/kpc^2]      0.520115
sigma(Rsat)[Msun/kpc^2]         0.499023

**Comment by Beilinson** [comment]
No significant negative correlation anywhere either
