### ISSUE TITLE
Lower the number of features

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vela_satellites#55]
By the Pearson correlations, find similarities

DOD - list of similarities

**Comment by Beilinson** [comment]
So far removed the following features: 'Mcg(Rsat)[Msun]','Mcg(Rcoldgass_0.9)[Msun]','sigma(R0.5kpc)[Msun/kpc^2]','density(R0.5kpc)[Msun/kpc^3]','density(R1kpc)[Msun/kpc^3]','Mstar(Rsat)[Msun]','Mdm(Rsat)[Msun]','center_Rvir[kpc]'
All had correlation to something else with 0.9 or higher.
