### ISSUE TITLE
Check possible swansong galaxies

### ISSUE THREAD

**Issue by Beilinson** [GalaxyHunters/Vela_satellites#56]
Weird S-Galaxies:
Some might be swan song, some are weird in that ssfr fluctuates a lot or starts with 0ssfr.
VELA_v2.Thick.04_tmp_00002
VELA_v2.Thick.01_tmp_00010
VELA_v2.Thick.04_tmp_00005
VELA_v2.Thick.07_tmp_00027
VELA_v2.Thick.07_tmp_00049
VELA_v2.Thick.07_tmp_00050
VELA_v2.Thick.07_tmp_00065
VELA_v2.Thick.07_tmp_00067
VELA_v2.Thick.08_tmp_00070
VELA_v2.Thick.13_tmp_00009
VELA_v2.Thick.15_tmp_00010
VELA_v2.Thick.24_tmp_00005
VELA_v2.Thick.27_tmp_00009
VELA_v2.Thick.27_tmp_00011
VELA_v2.Thick.28_tmp_00005
VELA_v2.Thick.29_tmp_00093
VELA_v2.Thick.30_tmp_00002
VELA_v2.Thick.34_tmp_00057

**Comment by tussbaum** [comment]
look at SFR at 0.5KPC I find it as a better parameter
