### ISSUE TITLE
Run shapes 

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vela_satellites#8]
DOD - full satellite catalog with dm radius and shapes.

* Adam, please fill here the columns you are going to add (not all of them, the idea)
** Adam, fil the columns titles in the comments.

**Comment by Beilinson** [comment]
Stars - 1,0.5,rsat,0.9coldgas
dm - 1,0.5,rsat,r_dm,r_dm_half
gas- 1,0.5,rsat,0.9coldgas,r_dm,r_dm_half
coldgas - 1,0.5,rsat,0.9coldgas,r_dm,r_dm_half
youngstars - 1,0.5,rsat,0.9coldgas
total = 1,0.5,rsat,0.9coldgas,r_dm,r_dm_half
